name: Makefile CI

on:
  workflow_call:

  workflow_dispatch:

  push:

  pull_request:
    branches:
      - main
      - 'release-\d.\d\d'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHELL: /bin/bash

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
        with:
          go-version-file: go.mod

      - name: Run lint
        run: make lint

      - name: Install
        run: make install-ginkgo

      - name: Run ginkgo Dry Run
        run: ginkgo run -vv -r --dry-run ./tests/
        env:
          ECO_DRY_RUN: true

      - name: Run unit tests
        run: make test
