name: Makefile CI

on:
  workflow_call:

  workflow_dispatch:

  push:

  pull_request:
    branches:
      - main
      - 'release-\d.\d\d'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHELL: /bin/bash
      GOLANGCI_LINT_CACHE: ${{ github.workspace }}/golangci-lint-cache

    steps:
      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.6

      - uses: actions/checkout@v4

      # Restore cache scoped by the OS and branch name (or target branch for
      # pull requests) and save per commit. By saving the cache per commit, the
      # restored cache is always up-to-date. Including the branch name ensures
      # that the caches are specific to each branch and allows PRs to restore
      # from their target branch.
      - name: Cache lint results
        uses: actions/cache@v4
        with:
          path: ${{ env.GOLANGCI_LINT_CACHE }}
          key: golangci-lint-${{ runner.os }}-${{ github.event_name == 'pull_request' && github.base_ref || github.ref }}-${{ github.sha }}
          restore-keys: |
            golangci-lint-${{ runner.os }}-${{ github.event_name == 'pull_request' && github.base_ref || github.ref }}
      
      - name: Run lint
        run: make lint

      - name: Install
        run: make install-ginkgo

      - name: Run ginkgo Dry Run
        run: ginkgo run -vv -r --dry-run ./tests/
        env:
          ECO_DRY_RUN: true
      
      - name: Run unit tests
        run: make test
